FROM node:12 AS build

WORKDIR /opt/app

COPY heroes-web/package.json ./
RUN npm install
RUN npm install -g @angular/cli@10.0.4

COPY heroes-web ./

RUN ng build --prod --output-path=dist

#### prod img ####

FROM nginx:latest 

COPY --from=build /opt/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
